### ISSUE TITLE
Building the project

### ISSUE THREAD

**Issue by JunkBeat** [AhmedAhmedEG/UnityTypeTreeGenerator#1]
Hello! I did not find instructions regarding Project Building in the Readme. Please can you help?

**Comment by AhmedAhmedEG** [comment]
The instructions is not special, I have given all the project files there, you probably did something wrong while setting up the project, also I provided the .sln file, it should have everything setup on it already.

**Comment by AhmedAhmedEG** [comment]
Normally, you just need too load the .sln file and hit build, at least send me the errors you are getting so we can think about it.

**Comment by JunkBeat** [comment]
Alright. After starting the project, I get the following errors and warnings. I don't know what could be causing this.

![image](https://github.com/AhmedAhmedEG/Unity-Type-Tree-Generator/assets/61349612/faefd159-fce5-496d-840b-ce9f6e7f5d78)

I tried adding the missing project from here https://github.com/nesrak1/AssetsTools.NET/tree/main
but unfortunately this did not solve the problem:

> Error	NU1105	Unable to find project information for 'C:\Users\<username>\Desktop\typetree\project\AssetTools.NET\AssetsTools.NET.csproj'. If you are using Visual Studio, this may be because the project is unloaded or not part of the current solution so run a restore from the command-line. Otherwise, the project file may be invalid or missing targets required for restore.

**Comment by AhmedAhmedEG** [comment]
You have missed it up, the project references a modified AssetsTools.MonoCecil project that exist inside the project folder.
Yours is referencing AssetsTools.net only for some reason.

It should reference "AssetsTools.NET.MonoCecil.csproj" and not "AssetsTools.NET.csproj"

**Comment by JunkBeat** [comment]
I found a solution! You probably forgot to remove the dependency.

![image](https://github.com/AhmedAhmedEG/Unity-Type-Tree-Generator/assets/61349612/a904b956-f72e-4e4a-80c0-4104595a7ec0)

**Comment by AhmedAhmedEG** [comment]
Weird, this dependency is needed but I included it as a DLL inside the project folder.

EDIT: I see now, seems like I uploaded an older sln that was using AssetsTools.NET project rather than the dll.

**Comment by AhmedAhmedEG** [comment]
Ok, I have uploaded the updated files, they include the csproj of AssetsTools.MonoCecil and three dlls.
